In [1]:
import cv2
import numpy as np
from tensorflow.keras.applications.mobilenet_v2 import preprocess_input
from tensorflow.keras.preprocessing.image import img_to_array
from tensorflow.keras.models import load_model

video = cv2.VideoCapture(0)

prototxtPath = "deploy.prototxt.txt"
weightsPath = "res10_300x300_ssd_iter_140000_fp16.caffemodel"
net = cv2.dnn.readNetFromCaffe(prototxtPath, weightsPath)

print("[INFO] loading face mask detector model...")
model = load_model("mask_prediction.h5")
index=["masked","Unmasked"]
while True:
    _, frame = video.read()
    if frame is None:
        break
    frame=cv2.resize(frame,(640,480))    
    h,w = frame.shape[:2]
    
    blob = cv2.dnn.blobFromImage(cv2.resize(frame, (300, 300)), 1.0,
(300, 300), (104.0, 117.0, 123.0))
    print("[INFO] computing face detections...")
    net.setInput(blob)
    detections = net.forward()
    
    for i in range(0 , detections.shape[2]):
        confidence = detections[0, 0, i,2]
        if confidence > 0.5:
            box = detections[0, 0, i, 3:7] * np.array([w, h, w, h])
            (x,y,W,H) = box.astype("int")
            #print("sx: ",x,"ex",w,"sy",y,"ey",h)
            cv2.rectangle(frame,(x,y),(W,H),(0,255,0),2)
            
            crop = frame[y:H, x:W]
            if crop is None:
                continue
            roi=cv2.resize(crop,(64,64))
            roi = roi.astype("float")/ 255.0
            roi = cv2.flip(roi,1,1)
            img_array = img_to_array(roi)
            face = np.expand_dims(process, axis=0)

            label=index[np.argmax(model.predict(face))]
            print(model.predict(face))
            color = (0,255,0) if label == "masked" else (0,0,255)
            cv2.putText(frame, label, (x,y-10), cv2.FONT_HERSHEY_SIMPLEX,0.6,
                        color,2)
            cv2.rectangle(frame,(x,y),(W,H),color,2)
         
    cv2.imshow("Output",frame)
    
    key = cv2.waitKey(1)
    if key == ord('q'):
        break

video.release()
cv2.destroyAllWindows()


C:\Users\prince\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\prince\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\prince\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\prince\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:519: FutureWarning: P

[INFO] loading face mask detector model...
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
[INFO] computing face detections...
[INFO] computing face detections...
[INFO] computing face detections...
[INFO] computing face detections...
[INFO] computing face detections...
[INFO] computing face detections...
[INFO] computing face detections...
[INFO] computing face detections...
[INFO] computing face detections...
[INFO] computing face detections...
[INFO] computing face detections...
[INFO] computing face detections...
[INFO] computing face detections...
[INFO] computing face detections...
[INFO] computing face detections...
[INFO] computing face detections...
[INFO] computing face detections...
[INFO] computing face detections...
[INFO] computing face detections...
[INFO] computing face detections...
[INFO] computing face detections...
[INFO] computing face detections...
[INFO] computing face detections...
[INFO] computing face detections...

[INFO] computing face detections...
[INFO] computing face detections...
[INFO] computing face detections...
[INFO] computing face detections...
[INFO] computing face detections...
[INFO] computing face detections...
[INFO] computing face detections...
[INFO] computing face detections...
[INFO] computing face detections...
[INFO] computing face detections...
[INFO] computing face detections...
[INFO] computing face detections...
[INFO] computing face detections...
[INFO] computing face detections...
[INFO] computing face detections...
[INFO] computing face detections...
[INFO] computing face detections...
[INFO] computing face detections...
[INFO] computing face detections...
[INFO] computing face detections...
[INFO] computing face detections...
[INFO] computing face detections...
[INFO] computing face detections...
[INFO] computing face detections...
[INFO] computing face detections...
[INFO] computing face detections...
[INFO] computing face detections...
[INFO] computing face detect

[INFO] computing face detections...
[INFO] computing face detections...
[INFO] computing face detections...
[INFO] computing face detections...
[INFO] computing face detections...
[INFO] computing face detections...
[INFO] computing face detections...
[INFO] computing face detections...
[INFO] computing face detections...
[INFO] computing face detections...
[INFO] computing face detections...
[INFO] computing face detections...
[INFO] computing face detections...
[INFO] computing face detections...
[INFO] computing face detections...
[[1.0000000e+00 1.6426907e-27]]
[INFO] computing face detections...
[[1.0000000e+00 1.6409497e-27]]
[INFO] computing face detections...
[INFO] computing face detections...
[INFO] computing face detections...
[[1.0000000e+00 1.6521929e-27]]
[INFO] computing face detections...
[INFO] computing face detections...
[INFO] computing face detections...
[INFO] computing face detections...
[INFO] computing face detections...
[INFO] computing face detections...
[INF

[INFO] computing face detections...
[INFO] computing face detections...
[INFO] computing face detections...
[INFO] computing face detections...
[INFO] computing face detections...
[INFO] computing face detections...
[INFO] computing face detections...
[INFO] computing face detections...
[INFO] computing face detections...
